### ISSUE TITLE
Regex to prevent inaccurate filling

### ISSUE THREAD

**Issue by CW-UK** [CW-UK/WMEOneNetworkHelper#3]
Use regex to obtain ref from URL for malformed descriptions such as:

`URL: https://one.network/?GBTMI28007804 Schedule: Monday:`

**Comment by JamesKingdom** [comment]
Regex? I'd rather not

**Comment by CW-UK** [comment]
`/(?:GB|GBTMI)(\d{5,})/`

`/\d{5,}/g`

**Comment by JamesKingdom** [comment]
Very nice
